// Waymark - IT Security & Consultancy
// Global site configuration

export const SITE_TITLE = "Waymark";
export const SITE_DESCRIPTION = "Enterprise IT Security, Cloud, & Network Solutions. Productized security services with fixed scope, clear outcomes, and measurable results.";

export const SITE_TAGLINE = "Security. Simplified.";

export const COMPANY_INFO = {
  name: "Waymark",
  tagline: "IT Security & Consultancy",
  email: "hello@waymark.io",
  phone: "+1 (555) 123-4567",
  address: "123 Security Lane, Tech District",
};

export const NAV_LINKS = [
  { href: "/", label: "Home" },
  { href: "/solutions/microsoft-365", label: "Microsoft 365" },
  { href: "/solutions/networking", label: "Networking" },
  { href: "/services", label: "Services" },
  { href: "/about", label: "About" },
  { href: "/blog", label: "Blog" },
  { href: "/contact", label: "Contact" },
];

export const SOCIAL_LINKS = {
  linkedin: "https://linkedin.com/company/waymark",
  twitter: "https://twitter.com/waymark",
  github: "https://github.com/waymark",
};

// Service type definitions
export type ServiceType = "assessment" | "implementation" | "managed";

export interface Service {
  id: string;
  title: string;
  shortTitle?: string;
  description: string;
  outcome: string;
  icon: string;
  category: string;
  types: ServiceType[];
  timeframe?: string;
  deliverables: string[];
  includes?: string[];
  featured?: boolean;
}

export interface ServiceCategory {
  id: string;
  title: string;
  description: string;
  icon: string;
  services: Service[];
}

// 12 Flagship Products (shown prominently)
export const FLAGSHIP_SERVICES: Service[] = [
  {
    id: "m365-security-assessment",
    title: "Microsoft 365 Security Assessment",
    shortTitle: "M365 Assessment",
    description: "Comprehensive evaluation of your Microsoft 365 security posture with actionable recommendations.",
    outcome: "Understand exposure and tighten baseline controls across your entire Microsoft 365 tenant.",
    icon: "microsoft",
    category: "microsoft-365",
    types: ["assessment"],
    timeframe: "5-10 days",
    deliverables: [
      "Executive summary with risk score",
      "Technical findings report",
      "Top 20 prioritized fixes backlog",
      "30/60/90 day remediation roadmap",
    ],
    featured: true,
  },
  {
    id: "vulnerability-management",
    title: "Vulnerability Management Program",
    shortTitle: "Vuln Management",
    description: "Ongoing visibility of vulnerabilities with tracked remediation and measurable risk reduction.",
    outcome: "Continuous vulnerability discovery with prioritized remediation and trend reporting.",
    icon: "shield",
    category: "managed-security",
    types: ["managed"],
    timeframe: "Monthly",
    deliverables: [
      "Monthly vulnerability report",
      "Remediation ticket backlog",
      "Risk trend summary",
      "Retest validation",
    ],
    featured: true,
  },
  {
    id: "intune-implementation",
    title: "Intune Baseline Implementation",
    shortTitle: "Intune Setup",
    description: "Complete Intune deployment with security baselines, compliance policies, and app management.",
    outcome: "Modern endpoint management with security-first configuration.",
    icon: "device",
    category: "intune",
    types: ["implementation"],
    timeframe: "2-4 weeks",
    deliverables: [
      "Configured Intune tenant",
      "Security baseline policies",
      "Compliance policies",
      "App deployment configuration",
      "Rollout documentation",
    ],
    featured: true,
  },
  {
    id: "unifi-network-deployment",
    title: "UniFi Network Deployment",
    shortTitle: "UniFi Deploy",
    description: "Enterprise-grade UniFi network infrastructure with proper segmentation and security.",
    outcome: "Installed, secured, and documented network infrastructure.",
    icon: "network",
    category: "networking",
    types: ["implementation"],
    timeframe: "1-2 weeks",
    deliverables: [
      "Network configuration",
      "VLAN segmentation",
      "Network diagrams",
      "Handover documentation",
      "Support plan option",
    ],
    featured: true,
  },
  {
    id: "ai-readiness-strategy",
    title: "AI Readiness & Strategy",
    shortTitle: "AI Strategy",
    description: "A practical AI plan tied to business workflows, not hype.",
    outcome: "Clear AI roadmap with prioritized use cases and implementation plan.",
    icon: "ai",
    category: "ai-services",
    types: ["assessment"],
    timeframe: "2-4 weeks",
    deliverables: [
      "AI roadmap document",
      "Prioritized use cases",
      "Pilot plan",
      "Success metrics",
      "Risk assessment",
    ],
    featured: true,
  },
  {
    id: "conditional-access-hardening",
    title: "Conditional Access Hardening",
    shortTitle: "CA Hardening",
    description: "Lock down access to your Microsoft 365 environment with properly configured Conditional Access.",
    outcome: "Zero-trust access controls with policy-based protection.",
    icon: "lock",
    category: "microsoft-365",
    types: ["implementation"],
    timeframe: "1-2 weeks",
    deliverables: [
      "Conditional Access policy set",
      "Named locations configuration",
      "Emergency access procedures",
      "Testing documentation",
    ],
    featured: true,
  },
  {
    id: "incident-response-retainer",
    title: "Incident Response Retainer",
    shortTitle: "IR Retainer",
    description: "Priority access and prepared runbooks before something goes wrong.",
    outcome: "Rapid response capability with pre-established procedures.",
    icon: "alert",
    category: "incident-response",
    types: ["managed"],
    timeframe: "Monthly/Quarterly",
    deliverables: [
      "Agreed response hours",
      "IR plan and runbooks",
      "Tabletop exercise",
      "Periodic readiness checks",
    ],
    featured: true,
  },
  {
    id: "google-microsoft-migration",
    title: "Google to Microsoft Migration",
    shortTitle: "G2M Migration",
    description: "Move users and data from Google Workspace to Microsoft 365 with minimal disruption.",
    outcome: "Complete migration with identity, mail, and data preserved.",
    icon: "migration",
    category: "migration",
    types: ["implementation"],
    timeframe: "2-6 weeks",
    deliverables: [
      "Migration plan",
      "Identity strategy",
      "Executed migration",
      "Post-migration checklist",
      "Support window",
    ],
    featured: true,
  },
  {
    id: "defender-endpoint-onboarding",
    title: "Defender for Endpoint Onboarding",
    shortTitle: "MDE Setup",
    description: "Endpoints protected with Microsoft Defender, alerts usable, onboarding complete.",
    outcome: "Full endpoint protection with actionable security alerts.",
    icon: "endpoint",
    category: "microsoft-365",
    types: ["implementation"],
    timeframe: "1-2 weeks",
    deliverables: [
      "Onboarding configuration",
      "Policy baseline",
      "Exclusions review",
      "SOC-lite playbook",
      "Tuning documentation",
    ],
    featured: true,
  },
  {
    id: "copilot-readiness",
    title: "Microsoft 365 Copilot Readiness",
    shortTitle: "Copilot Prep",
    description: "Prepare your environment for safe and effective Copilot deployment.",
    outcome: "Copilot is useful and safe from day one.",
    icon: "ai",
    category: "ai-services",
    types: ["assessment", "implementation"],
    timeframe: "2-3 weeks",
    deliverables: [
      "Copilot readiness report",
      "Permissions hygiene review",
      "Sensitivity labels approach",
      "Remediation backlog",
      "Pilot rollout plan",
    ],
    featured: true,
  },
  {
    id: "soc-lite-monitoring",
    title: "SOC-lite Monitoring Foundations",
    shortTitle: "SOC-lite",
    description: "Actionable alerting without a full SOC investment.",
    outcome: "Security monitoring with clear escalation procedures.",
    icon: "monitor",
    category: "managed-security",
    types: ["managed"],
    timeframe: "Monthly",
    deliverables: [
      "Log retention guidance",
      "Alert catalogue",
      "Triage workflow",
      "Weekly security summary",
      "Escalation runbooks",
    ],
    featured: true,
  },
  {
    id: "zero-trust-starter",
    title: "Zero Trust Starter Package",
    shortTitle: "Zero Trust",
    description: "Device compliance and Conditional Access working together for zero-trust access.",
    outcome: "Trust nothing, verify everything - implemented practically.",
    icon: "shield",
    category: "intune",
    types: ["implementation"],
    timeframe: "2-3 weeks",
    deliverables: [
      "Compliance policies",
      "Conditional Access integration",
      "Device health attestation",
      "Rollout plan",
      "User communication",
    ],
    featured: true,
  },
];

// Full Service Catalogue by Category
export const SERVICE_CATEGORIES: ServiceCategory[] = [
  {
    id: "managed-security",
    title: "Managed Security Programs",
    description: "Recurring security services for continuous protection and compliance.",
    icon: "shield-check",
    services: [
      {
        id: "vulnerability-management",
        title: "Vulnerability Management Program",
        description: "Ongoing visibility of vulnerabilities, tracked remediation, and measurable risk reduction.",
        outcome: "Continuous vulnerability discovery with prioritized remediation.",
        icon: "shield",
        category: "managed-security",
        types: ["managed"],
        timeframe: "Monthly",
        deliverables: ["Monthly vulnerability report", "Remediation tracking", "Retest validation", "Risk register", "Trend analysis"],
      },
      {
        id: "attack-surface-management",
        title: "Attack Surface Management",
        description: "Discover and reduce internet-exposed risk from unknown assets and drift.",
        outcome: "Complete visibility of your external attack surface.",
        icon: "globe",
        category: "managed-security",
        types: ["managed"],
        timeframe: "Monthly",
        deliverables: ["Asset inventory", "Exposure findings", "Monthly drift report", "Fix plan"],
      },
      {
        id: "bec-protection",
        title: "BEC Protection & Email Security",
        description: "Reduce invoice fraud and impersonation risk with email security monitoring.",
        outcome: "Tightened email security posture with continuous monitoring.",
        icon: "mail",
        category: "managed-security",
        types: ["managed"],
        timeframe: "Monthly",
        deliverables: ["Monthly email risk summary", "Policy change log", "DMARC reporting", "Recommendations"],
      },
      {
        id: "soc-lite",
        title: "SOC-lite Monitoring Foundations",
        description: "Actionable alerting without a full SOC.",
        outcome: "Security monitoring that fits your budget and team.",
        icon: "monitor",
        category: "managed-security",
        types: ["managed"],
        timeframe: "Monthly",
        deliverables: ["Weekly security summary", "Alert runbooks", "Escalation flow", "Triage workflow"],
      },
      {
        id: "dark-web-monitoring",
        title: "Dark Web Exposure Monitoring",
        description: "Identify leaked credentials early and reduce account takeover risk.",
        outcome: "Early warning of credential exposure.",
        icon: "eye",
        category: "managed-security",
        types: ["managed"],
        timeframe: "Monthly",
        deliverables: ["Exposure alerts", "Remediation workflow", "Monthly summary", "Response actions"],
      },
      {
        id: "backup-recovery-assurance",
        title: "Backup & Recovery Assurance",
        description: "Confirm you can actually recover, not just that you have backups.",
        outcome: "Validated recovery capability with tested procedures.",
        icon: "database",
        category: "managed-security",
        types: ["managed"],
        timeframe: "Quarterly",
        deliverables: ["Recovery plan", "Test results", "Gaps list", "Improvements backlog"],
      },
    ],
  },
  {
    id: "microsoft-365",
    title: "Microsoft 365 Platform",
    description: "Security and configuration services for Microsoft 365 environments.",
    icon: "microsoft",
    services: [
      {
        id: "m365-tenant-management",
        title: "Microsoft 365 Tenant Management",
        description: "Ongoing tenant operations with governance and security.",
        outcome: "Professionally managed Microsoft 365 tenant.",
        icon: "settings",
        category: "microsoft-365",
        types: ["managed"],
        timeframe: "Monthly",
        deliverables: ["Monthly tenant report", "Change log", "Quarterly roadmap refresh"],
      },
      {
        id: "m365-security-assessment",
        title: "Microsoft 365 Security Assessment",
        description: "Comprehensive evaluation of your M365 security posture.",
        outcome: "Clear understanding of security gaps and priorities.",
        icon: "search",
        category: "microsoft-365",
        types: ["assessment"],
        timeframe: "5-10 days",
        deliverables: ["Executive summary", "Technical report", "Top 20 fixes", "30/60/90 plan"],
      },
      {
        id: "conditional-access-hardening",
        title: "Conditional Access Hardening",
        description: "Implement zero-trust access controls.",
        outcome: "Policy-based access protection.",
        icon: "lock",
        category: "microsoft-365",
        types: ["implementation"],
        timeframe: "1-2 weeks",
        deliverables: ["CA policy set", "Named locations", "Emergency access", "Testing docs"],
      },
      {
        id: "mfa-modernisation",
        title: "MFA & Authentication Modernisation",
        description: "Move to modern, phishing-resistant authentication.",
        outcome: "Secure authentication across your organization.",
        icon: "key",
        category: "microsoft-365",
        types: ["implementation"],
        timeframe: "1-2 weeks",
        deliverables: ["Authentication policy", "Migration plan", "User communication", "Rollout support"],
      },
      {
        id: "pam-admin-hygiene",
        title: "Privileged Access Management",
        description: "Reduce blast radius and tighten privileged access.",
        outcome: "Protected admin access with proper controls.",
        icon: "user-shield",
        category: "microsoft-365",
        types: ["implementation", "managed"],
        timeframe: "2-3 weeks",
        deliverables: ["Break-glass setup", "Admin identity separation", "PIM rollout", "Operating procedures"],
      },
      {
        id: "defender-office365",
        title: "Defender for Office 365 Tuning",
        description: "Optimize email protection and reduce false positives.",
        outcome: "Effective email security with minimal friction.",
        icon: "mail-shield",
        category: "microsoft-365",
        types: ["implementation"],
        timeframe: "1 week",
        deliverables: ["Policy configuration", "Safe links/attachments", "Tuning report", "Alert setup"],
      },
      {
        id: "defender-endpoint",
        title: "Defender for Endpoint Onboarding",
        description: "Complete endpoint protection deployment.",
        outcome: "Protected endpoints with actionable alerts.",
        icon: "endpoint",
        category: "microsoft-365",
        types: ["implementation"],
        timeframe: "1-2 weeks",
        deliverables: ["Onboarding config", "Policy baseline", "SOC-lite playbook", "Tuning notes"],
      },
      {
        id: "defender-cloud-apps",
        title: "Defender for Cloud Apps",
        description: "Control risky SaaS usage and third-party app risk.",
        outcome: "Shadow IT visibility and OAuth app control.",
        icon: "cloud",
        category: "microsoft-365",
        types: ["implementation"],
        timeframe: "1-2 weeks",
        deliverables: ["App discovery", "OAuth review", "Governance recommendations", "Monitoring setup"],
      },
      {
        id: "purview-foundations",
        title: "Purview Foundations",
        description: "Data protection with sensitivity labels and DLP.",
        outcome: "Protected sensitive data across Microsoft 365.",
        icon: "tag",
        category: "microsoft-365",
        types: ["implementation"],
        timeframe: "2-3 weeks",
        deliverables: ["Label taxonomy", "DLP policies", "Auto-labeling rules", "User training"],
      },
      {
        id: "logging-alerting",
        title: "Logging, Audit & Alerting Baseline",
        description: "Security operations foundation with proper logging.",
        outcome: "Visibility into security events.",
        icon: "activity",
        category: "microsoft-365",
        types: ["implementation"],
        timeframe: "1 week",
        deliverables: ["Audit configuration", "Alert rules", "Retention settings", "Response procedures"],
      },
      {
        id: "collaboration-security",
        title: "Teams & SharePoint Security",
        description: "Secure collaboration without blocking productivity.",
        outcome: "Protected collaboration with appropriate sharing controls.",
        icon: "users",
        category: "microsoft-365",
        types: ["assessment", "implementation"],
        timeframe: "1-2 weeks",
        deliverables: ["Settings review", "External sharing controls", "Guest access policy", "Governance plan"],
      },
    ],
  },
  {
    id: "intune",
    title: "Intune & Endpoint Management",
    description: "Modern endpoint management and device security.",
    icon: "device",
    services: [
      {
        id: "intune-readiness",
        title: "Intune Readiness & Architecture",
        description: "Blueprint for a stable, supportable endpoint platform.",
        outcome: "Clear Intune deployment strategy.",
        icon: "blueprint",
        category: "intune",
        types: ["assessment"],
        timeframe: "1 week",
        deliverables: ["Intune blueprint", "Rollout plan", "Support model", "Prerequisites checklist"],
      },
      {
        id: "intune-implementation",
        title: "Intune Baseline Implementation",
        description: "Complete Intune deployment with security baselines.",
        outcome: "Managed endpoints with security-first configuration.",
        icon: "device",
        category: "intune",
        types: ["implementation"],
        timeframe: "2-4 weeks",
        deliverables: ["Configured tenant", "Security baselines", "Compliance policies", "App deployment"],
      },
      {
        id: "device-mobile-security",
        title: "Device & Mobile Security Package",
        description: "Compliance and protection across all device types.",
        outcome: "Consistent security across iOS, Android, and Windows.",
        icon: "mobile",
        category: "intune",
        types: ["implementation"],
        timeframe: "2-3 weeks",
        deliverables: ["Compliance model", "App protection policies", "Lost device response", "Admin runbook"],
      },
      {
        id: "windows-hardening",
        title: "Windows 10/11 Hardening",
        description: "Security baseline for Windows endpoints.",
        outcome: "Hardened Windows devices with reduced attack surface.",
        icon: "windows",
        category: "intune",
        types: ["implementation"],
        timeframe: "1-2 weeks",
        deliverables: ["Hardening baseline", "Attack surface reduction", "BitLocker config", "LAPS setup"],
      },
      {
        id: "zero-trust-starter",
        title: "Zero Trust Starter Package",
        description: "Device compliance integrated with Conditional Access.",
        outcome: "Zero-trust access control based on device health.",
        icon: "shield",
        category: "intune",
        types: ["implementation"],
        timeframe: "2-3 weeks",
        deliverables: ["Compliance policies", "CA integration", "Device attestation", "Rollout plan"],
      },
      {
        id: "intune-managed",
        title: "Managed Intune Operations",
        description: "Ongoing endpoint management and policy maintenance.",
        outcome: "Healthy, compliant endpoint fleet.",
        icon: "settings",
        category: "intune",
        types: ["managed"],
        timeframe: "Monthly",
        deliverables: ["Monthly health report", "Policy drift control", "Change requests", "Improvement backlog"],
      },
    ],
  },
  {
    id: "identity",
    title: "Identity & Access",
    description: "Entra ID security and access management.",
    icon: "user",
    services: [
      {
        id: "entra-security-review",
        title: "Entra ID Security Review",
        description: "Comprehensive identity security assessment.",
        outcome: "Secured identity infrastructure.",
        icon: "user-check",
        category: "identity",
        types: ["assessment"],
        timeframe: "3-5 days",
        deliverables: ["Security findings", "Configuration review", "Recommendations", "Priority actions"],
      },
      {
        id: "oauth-consent-cleanup",
        title: "OAuth App & Consent Cleanup",
        description: "Remove risky third-party access and lock down consent.",
        outcome: "Controlled third-party application access.",
        icon: "app",
        category: "identity",
        types: ["implementation"],
        timeframe: "1 week",
        deliverables: ["Risky apps list", "Changes applied", "Governance recommendations", "Monitoring setup"],
      },
      {
        id: "sso-onboarding",
        title: "SSO Application Onboarding",
        description: "Secure single sign-on for business applications.",
        outcome: "Streamlined, secure application access.",
        icon: "link",
        category: "identity",
        types: ["implementation"],
        timeframe: "Per app",
        deliverables: ["SSO configuration", "Access policies", "Testing", "Documentation"],
      },
      {
        id: "identity-governance",
        title: "Identity Governance Setup",
        description: "Access reviews, lifecycle management, and entitlement management.",
        outcome: "Automated identity governance.",
        icon: "workflow",
        category: "identity",
        types: ["implementation"],
        timeframe: "2-4 weeks",
        deliverables: ["Access reviews", "Lifecycle policies", "Entitlement packages", "Governance report"],
      },
    ],
  },
  {
    id: "google-workspace",
    title: "Google Workspace",
    description: "Security and management for Google Workspace environments.",
    icon: "google",
    services: [
      {
        id: "google-tenant-management",
        title: "Google Workspace Tenant Management",
        description: "Operational ownership with security posture maintained.",
        outcome: "Professionally managed Google Workspace.",
        icon: "settings",
        category: "google-workspace",
        types: ["managed"],
        timeframe: "Monthly",
        deliverables: ["Monthly tenant report", "Change log", "Security posture report"],
      },
      {
        id: "google-security-assessment",
        title: "Google Workspace Security Assessment",
        description: "Understand exposure and tighten baseline controls.",
        outcome: "Clear security improvement roadmap.",
        icon: "search",
        category: "google-workspace",
        types: ["assessment"],
        timeframe: "3-5 days",
        deliverables: ["Risk register", "Top fixes backlog", "Configuration review", "Recommendations"],
      },
    ],
  },
  {
    id: "migration",
    title: "Migration Services",
    description: "Cloud platform migrations with minimal disruption.",
    icon: "migration",
    services: [
      {
        id: "google-microsoft-migration",
        title: "Google to Microsoft Migration",
        description: "Complete migration from Google Workspace to Microsoft 365.",
        outcome: "Successful migration with data integrity.",
        icon: "migration",
        category: "migration",
        types: ["implementation"],
        timeframe: "2-6 weeks",
        deliverables: ["Migration plan", "Identity strategy", "Executed migration", "Post-migration support"],
      },
      {
        id: "tenant-consolidation",
        title: "Microsoft Tenant Consolidation",
        description: "Fix messy tenant structures and consolidate.",
        outcome: "Clean, well-governed tenant architecture.",
        icon: "merge",
        category: "migration",
        types: ["implementation"],
        timeframe: "4-8 weeks",
        deliverables: ["Target operating model", "Phased roadmap", "Implementation sprints", "Governance framework"],
      },
    ],
  },
  {
    id: "networking",
    title: "Network Infrastructure",
    description: "Enterprise-grade networking with UniFi and site technology.",
    icon: "network",
    services: [
      {
        id: "unifi-design",
        title: "UniFi Full Stack Design",
        description: "Complete design for Wi-Fi, switching, routing, and segmentation.",
        outcome: "Enterprise-ready network architecture.",
        icon: "blueprint",
        category: "networking",
        types: ["assessment"],
        timeframe: "1 week",
        deliverables: ["Design document", "Bill of materials", "Deployment plan", "Segmentation strategy"],
      },
      {
        id: "unifi-implementation",
        title: "UniFi Implementation & Configuration",
        description: "Professional UniFi deployment with security hardening.",
        outcome: "Installed, secured, documented network.",
        icon: "network",
        category: "networking",
        types: ["implementation"],
        timeframe: "1-2 weeks",
        deliverables: ["Configuration", "VLAN setup", "Diagrams", "Handover documentation"],
      },
      {
        id: "unifi-site-tech",
        title: "UniFi Site Technology Deployment",
        description: "End-to-end site technology including cameras, access control, and phones.",
        outcome: "Unified site technology infrastructure.",
        icon: "building",
        category: "networking",
        types: ["implementation"],
        timeframe: "2-4 weeks",
        deliverables: ["Deployed systems", "Admin documentation", "Support plan", "Training"],
      },
      {
        id: "managed-network",
        title: "Managed Network Operations",
        description: "Ongoing network management and optimization.",
        outcome: "Stable network with proactive maintenance.",
        icon: "settings",
        category: "networking",
        types: ["managed"],
        timeframe: "Monthly",
        deliverables: ["Monthly health report", "Config backup", "Change log", "Firmware management"],
      },
    ],
  },
  {
    id: "web-security",
    title: "Web Security",
    description: "Web application security testing and monitoring.",
    icon: "globe",
    services: [
      {
        id: "web-vuln-assessment",
        title: "Web Application Security Assessment",
        description: "Comprehensive security testing of web applications.",
        outcome: "Identified vulnerabilities with remediation guidance.",
        icon: "search",
        category: "web-security",
        types: ["assessment"],
        timeframe: "1-2 weeks",
        deliverables: ["Vulnerability report", "Risk ratings", "Remediation guidance", "Retest option"],
      },
      {
        id: "web-vuln-monitoring",
        title: "Web Vulnerability Monitoring",
        description: "Continuous security scanning of public web presence.",
        outcome: "Clean public web footprint.",
        icon: "monitor",
        category: "web-security",
        types: ["managed"],
        timeframe: "Monthly",
        deliverables: ["Monthly web security report", "Remediation list", "Trend analysis"],
      },
      {
        id: "cicd-secrets-review",
        title: "CI/CD & Secrets Hygiene Review",
        description: "Reduce supply-chain and credential leakage risk.",
        outcome: "Secure development pipeline.",
        icon: "code",
        category: "web-security",
        types: ["assessment"],
        timeframe: "3-5 days",
        deliverables: ["Findings report", "Remediation checklist", "Best practices guide"],
      },
    ],
  },
  {
    id: "ai-services",
    title: "AI Services",
    description: "AI strategy, implementation, and security.",
    icon: "ai",
    services: [
      {
        id: "ai-readiness",
        title: "AI Readiness & Strategy",
        description: "Practical AI plan tied to business workflows.",
        outcome: "Clear AI roadmap with measurable outcomes.",
        icon: "ai",
        category: "ai-services",
        types: ["assessment"],
        timeframe: "2-4 weeks",
        deliverables: ["AI roadmap", "Use case priorities", "Pilot plan", "Success metrics", "Risk assessment"],
      },
      {
        id: "ai-governance",
        title: "AI Governance & Security Baseline",
        description: "Adoption without data leakage and shadow AI chaos.",
        outcome: "Controlled AI adoption with security guardrails.",
        icon: "shield",
        category: "ai-services",
        types: ["implementation"],
        timeframe: "1-2 weeks",
        deliverables: ["AI governance pack", "Acceptable use policy", "Controls backlog", "Rollout communications"],
      },
      {
        id: "copilot-readiness",
        title: "Microsoft 365 Copilot Readiness",
        description: "Prepare your environment for safe Copilot deployment.",
        outcome: "Copilot-ready environment with proper controls.",
        icon: "ai",
        category: "ai-services",
        types: ["assessment", "implementation"],
        timeframe: "2-3 weeks",
        deliverables: ["Readiness report", "Permissions review", "Sensitivity labels", "Pilot plan"],
      },
      {
        id: "ai-workflow-automation",
        title: "AI Workflow Automation",
        description: "Replace manual processes with AI-assisted workflows.",
        outcome: "Automated workflows with AI integration.",
        icon: "workflow",
        category: "ai-services",
        types: ["implementation"],
        timeframe: "2-4 weeks",
        deliverables: ["Implemented workflows", "Documentation", "Training", "Handover"],
      },
      {
        id: "ai-pilot",
        title: "AI Pilot Program",
        description: "Controlled pilot with measured outcomes.",
        outcome: "Validated AI use cases with scale plan.",
        icon: "beaker",
        category: "ai-services",
        types: ["implementation"],
        timeframe: "30-60 days",
        deliverables: ["Pilot results", "Success metrics", "Feedback analysis", "Scale plan"],
      },
      {
        id: "ai-training",
        title: "AI Training for Staff",
        description: "Role-based training for safe and effective AI use.",
        outcome: "AI-capable workforce.",
        icon: "graduation",
        category: "ai-services",
        types: ["implementation"],
        timeframe: "1-2 days",
        deliverables: ["Training sessions", "Take-home guides", "Policy acknowledgment", "Prompt library"],
      },
    ],
  },
  {
    id: "incident-response",
    title: "Incident Response",
    description: "Incident response services and retainers.",
    icon: "alert",
    services: [
      {
        id: "compromise-assessment",
        title: "Compromise Assessment",
        description: "Quick answer to 'are we currently breached?'",
        outcome: "Confirmed security status with next steps.",
        icon: "search",
        category: "incident-response",
        types: ["assessment"],
        timeframe: "2-3 days",
        deliverables: ["Findings report", "Containment actions", "Remediation plan", "Next steps"],
      },
      {
        id: "ir-retainer",
        title: "Incident Response Retainer",
        description: "Priority access with prepared runbooks.",
        outcome: "Rapid response capability when needed.",
        icon: "shield",
        category: "incident-response",
        types: ["managed"],
        timeframe: "Monthly/Quarterly",
        deliverables: ["Response hours", "IR plan", "Tabletop exercises", "Readiness checks"],
      },
      {
        id: "ir-workshop",
        title: "Incident Response Workshop",
        description: "Prepare your team with tabletop exercises.",
        outcome: "Trained team with tested procedures.",
        icon: "users",
        category: "incident-response",
        types: ["implementation"],
        timeframe: "1 day",
        deliverables: ["Workshop delivery", "Tabletop scenarios", "Lessons learned", "Improvement plan"],
      },
    ],
  },
  {
    id: "configuration-reviews",
    title: "Security Configuration Reviews",
    description: "Quick, focused security configuration assessments.",
    icon: "check",
    services: [
      {
        id: "secure-defaults-review",
        title: "Secure Defaults vs Conditional Access",
        description: "Confirm you're not relying on weak defaults.",
        outcome: "Validated security configuration.",
        icon: "check",
        category: "configuration-reviews",
        types: ["assessment"],
        timeframe: "2-3 days",
        deliverables: ["Baseline scorecard", "Target state recommendations", "Priority actions"],
      },
      {
        id: "sharepoint-sharing-review",
        title: "SharePoint External Sharing Review",
        description: "Collaboration without accidental exposure.",
        outcome: "Secure external sharing configuration.",
        icon: "share",
        category: "configuration-reviews",
        types: ["assessment"],
        timeframe: "1-2 days",
        deliverables: ["Settings review", "Changes list", "Retest verification"],
      },
      {
        id: "teams-security-review",
        title: "Teams External/Federation Review",
        description: "Reduce meeting and external chat risk.",
        outcome: "Secured Teams collaboration.",
        icon: "users",
        category: "configuration-reviews",
        types: ["assessment"],
        timeframe: "1-2 days",
        deliverables: ["Policy review", "Recommendations", "Rollout plan"],
      },
      {
        id: "vpn-remote-access-review",
        title: "VPN & Remote Access Review",
        description: "Reduce exposure and tighten remote access.",
        outcome: "Hardened remote access infrastructure.",
        icon: "lock",
        category: "configuration-reviews",
        types: ["assessment"],
        timeframe: "2-3 days",
        deliverables: ["Architecture review", "Hardening actions", "Runbook"],
      },
      {
        id: "firewall-segmentation-review",
        title: "Firewall & Network Segmentation Review",
        description: "Reduce lateral movement risk.",
        outcome: "Improved network security posture.",
        icon: "network",
        category: "configuration-reviews",
        types: ["assessment"],
        timeframe: "2-3 days",
        deliverables: ["Segmentation improvements", "Rules cleanup plan", "Best practices"],
      },
    ],
  },
];

// Recurring Plans (Security Core / Plus / Complete)
export interface RecurringPlan {
  id: string;
  name: string;
  tagline: string;
  description: string;
  monthlyPrice: string;
  featured?: boolean;
  includes: string[];
  addOns?: string[];
}

export const RECURRING_PLANS: RecurringPlan[] = [
  {
    id: "security-core",
    name: "Security Core",
    tagline: "Essential Protection",
    description: "Foundational security monitoring and management for growing businesses.",
    monthlyPrice: "Contact us",
    includes: [
      "Vulnerability Management (monthly scan)",
      "Dark Web Exposure Monitoring",
      "Microsoft 365 Secure Score monitoring",
      "Monthly security summary report",
      "Email support",
      "Quarterly security review call",
    ],
    addOns: [
      "SOC-lite Monitoring",
      "Backup & Recovery Assurance",
    ],
  },
  {
    id: "security-plus",
    name: "Security Plus",
    tagline: "Most Popular",
    description: "Comprehensive security operations for security-conscious organizations.",
    monthlyPrice: "Contact us",
    featured: true,
    includes: [
      "Everything in Security Core",
      "Attack Surface Management",
      "BEC Protection & Email Security",
      "SOC-lite Monitoring Foundations",
      "Microsoft 365 Tenant Management",
      "Monthly security operations call",
      "Priority email & phone support",
      "4-hour response SLA",
    ],
    addOns: [
      "Managed Intune Operations",
      "Managed Network Operations",
      "Incident Response Retainer",
    ],
  },
  {
    id: "security-complete",
    name: "Security Complete",
    tagline: "Full Coverage",
    description: "Enterprise-grade security program with dedicated support and rapid response.",
    monthlyPrice: "Contact us",
    includes: [
      "Everything in Security Plus",
      "Incident Response Retainer (included)",
      "Backup & Recovery Assurance (quarterly)",
      "Managed Intune Operations",
      "Virtual CISO advisory hours",
      "Bi-weekly security operations call",
      "Dedicated account manager",
      "2-hour response SLA",
      "Annual penetration test",
      "Compliance monitoring & reporting",
    ],
  },
];

// Helper function to get services by category
export function getServicesByCategory(categoryId: string): Service[] {
  const category = SERVICE_CATEGORIES.find(c => c.id === categoryId);
  return category?.services || [];
}

// Helper function to get all featured services
export function getFeaturedServices(): Service[] {
  return FLAGSHIP_SERVICES.filter(s => s.featured);
}

// Helper function to get service by ID
export function getServiceById(serviceId: string): Service | undefined {
  for (const category of SERVICE_CATEGORIES) {
    const service = category.services.find(s => s.id === serviceId);
    if (service) return service;
  }
  return FLAGSHIP_SERVICES.find(s => s.id === serviceId);
}
