// Waymark - IT Security & Consultancy
// Global site configuration

export const SITE_TITLE = "Waymark";
export const SITE_DESCRIPTION = "Enterprise IT Security, Cloud, & Network Solutions. Productized security services with fixed scope, clear outcomes, and measurable results.";
export const SITE_TAGLINE = "Security. Simplified.";

export const COMPANY_INFO = {
  name: "Waymark",
  tagline: "IT Security & Consultancy",
  email: "hello@waymark.io",
  phone: "+1 (555) 123-4567",
  address: "123 Security Lane, Tech District",
};

export const NAV_LINKS = [
  { href: "/", label: "Home" },
  { href: "/solutions/microsoft-365", label: "Microsoft 365" },
  { href: "/solutions/networking", label: "Networking" },
  { href: "/services", label: "Services" },
  { href: "/about", label: "About" },
  { href: "/blog", label: "Blog" },
  { href: "/contact", label: "Contact" },
];

export const SOCIAL_LINKS = {
  linkedin: "https://linkedin.com/company/waymark",
  twitter: "https://twitter.com/waymark",
  github: "https://github.com/waymark",
};

// Service type definitions
export type ServiceType = "assessment" | "implementation" | "managed";

export interface Service {
  id: string;
  title: string;
  shortTitle?: string;
  description: string;
  outcome: string;
  icon: string;
  category: string;
  types: ServiceType[];
  timeframe?: string;
  deliverables: string[];
  includes?: string[];
  featured?: boolean;
}

export interface ServiceCategory {
  id: string;
  title: string;
  shortTitle: string;
  description: string;
  icon: string;
  color: string;
  services: Service[];
}

// =============================================================================
// COMPLETE SERVICE CATALOGUE - 12 Categories, 60+ Services
// =============================================================================

export const SERVICE_CATEGORIES: ServiceCategory[] = [
  // 1. MANAGED SECURITY PROGRAMS (Recurring Revenue)
  {
    id: "managed-security",
    title: "Managed Security Programs",
    shortTitle: "Managed Security",
    description: "Continuous protection with ongoing visibility, monitoring, and measurable risk reduction over time.",
    icon: "shield",
    color: "blue",
    services: [
      {
        id: "vulnerability-management",
        title: "Vulnerability Management Program",
        shortTitle: "Vuln Management",
        description: "Ongoing visibility of vulnerabilities, tracked remediation, and measurable risk reduction over time.",
        outcome: "Continuous vulnerability discovery with prioritized remediation and trend reporting.",
        icon: "shield",
        category: "managed-security",
        types: ["managed"],
        timeframe: "Monthly",
        includes: [
          "External vulnerability scanning",
          "Monthly detailed report",
          "Remediation tracking",
          "Retest validation",
          "Risk register maintenance",
          "Trend line analysis",
        ],
        deliverables: [
          "Monthly vulnerability report",
          "Ticket/backlog list",
          "Risk trend summary",
        ],
        featured: true,
      },
      {
        id: "attack-surface-management",
        title: "Attack Surface Management (ASM)",
        shortTitle: "ASM",
        description: "Discover and reduce internet-exposed risk from unknown assets and infrastructure drift.",
        outcome: "Complete visibility of your external attack surface with proactive risk reduction.",
        icon: "globe",
        category: "managed-security",
        types: ["managed"],
        timeframe: "Monthly",
        includes: [
          "Exposed services review",
          "Subdomain and DNS sprawl analysis",
          "Certificate and domain checks",
          "Basic hardening actions",
          "Cloudflare/DNS posture review",
        ],
        deliverables: [
          "Asset inventory",
          "Exposure findings",
          "Fix plan",
          "Monthly drift report",
        ],
      },
      {
        id: "bec-protection",
        title: "BEC Protection & Email Security Monitoring",
        shortTitle: "Email Security",
        description: "Reduce invoice fraud and impersonation risk while tightening your email security posture.",
        outcome: "Protected email environment with ongoing monitoring and continuous tuning.",
        icon: "mail",
        category: "managed-security",
        types: ["managed"],
        timeframe: "Monthly",
        includes: [
          "Policy monitoring",
          "Risky forwarding detection",
          "Mailbox rule checks",
          "DMARC reporting oversight",
          "Continuous tuning",
        ],
        deliverables: [
          "Monthly email risk summary",
          "Recommendations",
          "Policy change log",
        ],
      },
      {
        id: "soc-lite-monitoring",
        title: "SOC-lite Monitoring Foundations",
        shortTitle: "SOC-lite",
        description: "Actionable alerting without a full SOC - practical security monitoring for SMBs.",
        outcome: "Structured alerting with clear workflows and escalation procedures.",
        icon: "monitor",
        category: "managed-security",
        types: ["managed"],
        timeframe: "Monthly",
        includes: [
          "Log retention guidance",
          "Alert catalogue setup",
          "Triage workflow design",
          "Weekly review cadence",
          "Escalation plan",
        ],
        deliverables: [
          "Weekly security summary template",
          "Alert runbooks",
          "Escalation flow documentation",
        ],
      },
      {
        id: "dark-web-monitoring",
        title: "Dark Web Exposure Monitoring",
        shortTitle: "Dark Web Monitor",
        description: "Identify leaked credentials early and reduce account takeover risk.",
        outcome: "Early warning system for credential exposure with rapid response capability.",
        icon: "eye",
        category: "managed-security",
        types: ["managed"],
        timeframe: "Monthly",
        includes: [
          "Monitoring setup via reputable service",
          "Response workflow design",
          "Account protection actions",
        ],
        deliverables: [
          "Exposure alerts",
          "Remediation workflow",
          "Monthly summary report",
        ],
      },
      {
        id: "backup-recovery-assurance",
        title: "Backup & Recovery Assurance",
        shortTitle: "Backup Assurance",
        description: "Confirm you can actually recover - not just 'we have backups'.",
        outcome: "Verified recovery capability with tested procedures and documented gaps.",
        icon: "database",
        category: "managed-security",
        types: ["managed"],
        timeframe: "Monthly/Quarterly",
        includes: [
          "Coverage review",
          "Restore testing",
          "Ransomware recovery checklist",
        ],
        deliverables: [
          "Recovery plan",
          "Test results",
          "Gaps list",
          "Improvements backlog",
        ],
      },
    ],
  },

  // 2. MICROSOFT 365 PLATFORM SERVICES
  {
    id: "microsoft-365",
    title: "Microsoft 365 Platform Services",
    shortTitle: "Microsoft 365",
    description: "Complete M365 security from assessment to managed operations - your entire Microsoft estate secured.",
    icon: "microsoft",
    color: "purple",
    services: [
      {
        id: "m365-tenant-management",
        title: "Microsoft 365 Tenant Management",
        shortTitle: "Tenant Management",
        description: "Ongoing tenant operations with governance and security baked in.",
        outcome: "Professionally managed tenant with policy compliance and security hygiene maintained.",
        icon: "microsoft",
        category: "microsoft-365",
        types: ["managed"],
        timeframe: "Monthly",
        includes: [
          "Policy management",
          "Admin hygiene",
          "Secure Score hygiene",
          "Change control",
          "Monthly reporting",
        ],
        deliverables: [
          "Monthly tenant report",
          "Change log",
          "Quarterly roadmap refresh",
        ],
      },
      {
        id: "m365-security-assessment",
        title: "Microsoft 365 Tenant Security Assessment",
        shortTitle: "M365 Assessment",
        description: "Comprehensive evaluation of your Microsoft 365 security posture with actionable recommendations.",
        outcome: "Understand exposure and tighten baseline controls across your entire Microsoft 365 tenant.",
        icon: "search",
        category: "microsoft-365",
        types: ["assessment"],
        timeframe: "5-10 days",
        includes: [
          "Identity and access review",
          "Email security analysis",
          "Data protection assessment",
          "Compliance posture check",
          "Secure Score analysis",
        ],
        deliverables: [
          "Executive summary",
          "Technical report",
          "Top 20 fixes backlog",
          "30/60/90 day plan",
        ],
        featured: true,
      },
      {
        id: "conditional-access-hardening",
        title: "Conditional Access Hardening Sprint",
        shortTitle: "CA Hardening",
        description: "Lock down access to your Microsoft 365 environment with properly configured Conditional Access.",
        outcome: "Zero-trust access controls with policy-based protection.",
        icon: "lock",
        category: "microsoft-365",
        types: ["implementation"],
        timeframe: "1-2 weeks",
        deliverables: [
          "Conditional Access policy set",
          "Named locations configuration",
          "Emergency access procedures",
          "Testing documentation",
        ],
        featured: true,
      },
      {
        id: "mfa-modernisation",
        title: "MFA and Authentication Modernisation",
        shortTitle: "MFA Modernisation",
        description: "Move to phishing-resistant authentication with modern MFA methods.",
        outcome: "Strong authentication across all users with passwordless options enabled.",
        icon: "key",
        category: "microsoft-365",
        types: ["implementation"],
        timeframe: "1-2 weeks",
        includes: [
          "Current state assessment",
          "Authentication method rollout",
          "Legacy protocol disable plan",
          "User communication",
        ],
        deliverables: [
          "Authentication baseline",
          "Rollout plan",
          "User guides",
          "Completion report",
        ],
      },
      {
        id: "pam-admin-hygiene",
        title: "Privileged Access Management & Admin Hygiene",
        shortTitle: "PAM Setup",
        description: "Reduce blast radius and tighten privileged access across your environment.",
        outcome: "Secured admin access with proper separation and just-in-time elevation.",
        icon: "users",
        category: "microsoft-365",
        types: ["implementation", "managed"],
        timeframe: "2-3 weeks",
        includes: [
          "Break-glass account setup and testing",
          "Separate admin identities",
          "PIM rollout (where licensed)",
          "Admin workstation guidance",
        ],
        deliverables: [
          "Privileged access design",
          "Implemented controls",
          "Operating procedure",
        ],
      },
      {
        id: "defender-office-tuning",
        title: "Defender for Office 365 Tuning",
        shortTitle: "Defender O365",
        description: "Optimize your email protection with properly configured Defender for Office 365.",
        outcome: "Tuned email security with reduced false positives and improved threat detection.",
        icon: "mail-shield",
        category: "microsoft-365",
        types: ["implementation"],
        timeframe: "1 week",
        includes: [
          "Safe Links and Safe Attachments configuration",
          "Anti-phishing policy tuning",
          "Quarantine policy setup",
          "Alert configuration",
        ],
        deliverables: [
          "Configured policies",
          "Tuning documentation",
          "Monitoring setup",
        ],
      },
      {
        id: "defender-endpoint",
        title: "Defender for Endpoint Onboarding & Hardening",
        shortTitle: "Defender Endpoint",
        description: "Complete endpoint protection with Defender for Endpoint properly deployed and tuned.",
        outcome: "Endpoints protected with usable alerts and complete onboarding.",
        icon: "device",
        category: "microsoft-365",
        types: ["implementation"],
        timeframe: "2-3 weeks",
        includes: [
          "Onboarding plan",
          "Policy baseline",
          "Exclusions review",
          "Triage workflow setup",
        ],
        deliverables: [
          "Configured baseline",
          "SOC-lite playbook",
          "Tuning notes",
        ],
      },
      {
        id: "defender-cloud-apps",
        title: "Defender for Cloud Apps (Shadow IT / OAuth Control)",
        shortTitle: "MDCA Setup",
        description: "Control risky SaaS usage and third-party app risk with cloud app security.",
        outcome: "Visibility into shadow IT with governance over risky applications.",
        icon: "cloud",
        category: "microsoft-365",
        types: ["implementation"],
        timeframe: "1-2 weeks",
        includes: [
          "App discovery setup",
          "OAuth app review",
          "Governance recommendations",
        ],
        deliverables: [
          "Risk findings",
          "Controls plan",
          "Monitoring approach",
        ],
      },
      {
        id: "defender-identity",
        title: "Defender for Identity (Hybrid AD)",
        shortTitle: "MDI Setup",
        description: "Detect identity threats in hybrid Active Directory environments.",
        outcome: "Identity threat detection for on-premises AD with proper alerting.",
        icon: "user-shield",
        category: "microsoft-365",
        types: ["implementation"],
        timeframe: "1-2 weeks",
        includes: [
          "Readiness review",
          "Deployment guidance",
          "Alert tuning",
        ],
        deliverables: [
          "Rollout plan",
          "Alert runbooks",
        ],
      },
      {
        id: "purview-foundations",
        title: "Purview Foundations (Data Protection)",
        shortTitle: "Purview Setup",
        description: "Implement Microsoft Purview for data classification, labeling, and protection.",
        outcome: "Data protection framework with sensitivity labels and DLP policies.",
        icon: "file-lock",
        category: "microsoft-365",
        types: ["implementation"],
        timeframe: "2-4 weeks",
        includes: [
          "Classification scheme design",
          "Sensitivity label rollout",
          "DLP policy baseline",
          "User training materials",
        ],
        deliverables: [
          "Label taxonomy",
          "DLP policies",
          "Training deck",
          "Rollout plan",
        ],
      },
      {
        id: "logging-alerting-baseline",
        title: "Logging, Audit, and Alerting Baseline",
        shortTitle: "Logging Setup",
        description: "Ensure proper logging and alerting for security operations.",
        outcome: "Complete audit logging with actionable alerts and retention compliance.",
        icon: "activity",
        category: "microsoft-365",
        types: ["implementation"],
        timeframe: "1 week",
        includes: [
          "Audit log configuration",
          "Retention policy setup",
          "Alert rule creation",
          "SIEM integration guidance",
        ],
        deliverables: [
          "Logging configuration",
          "Alert catalogue",
          "Retention documentation",
        ],
      },
      {
        id: "collaboration-security",
        title: "Teams / SharePoint / OneDrive Security Controls",
        shortTitle: "Collaboration Security",
        description: "Secure your collaboration tools with proper sharing controls and governance.",
        outcome: "Protected collaboration environment with controlled external sharing.",
        icon: "share",
        category: "microsoft-365",
        types: ["assessment", "implementation"],
        timeframe: "1-2 weeks",
        includes: [
          "Teams security assessment",
          "SharePoint sharing review",
          "OneDrive sync controls",
          "Guest access configuration",
        ],
        deliverables: [
          "Security assessment",
          "Policy recommendations",
          "Implementation guide",
        ],
      },
    ],
  },

  // 3. INTUNE & ENDPOINT MANAGEMENT
  {
    id: "intune",
    title: "Intune & Endpoint Management",
    shortTitle: "Intune",
    description: "Modern endpoint management with Intune - from architecture to ongoing operations.",
    icon: "device",
    color: "cyan",
    services: [
      {
        id: "intune-readiness",
        title: "Intune Readiness & Architecture Review",
        shortTitle: "Intune Readiness",
        description: "Clear blueprint for a stable, supportable endpoint management platform.",
        outcome: "Documented architecture with clear rollout plan and support model.",
        icon: "blueprint",
        category: "intune",
        types: ["assessment"],
        timeframe: "1 week",
        includes: [
          "Tenant prerequisites review",
          "Licensing considerations",
          "Enrollment approach design",
          "Deployment rings strategy",
          "Baseline design",
        ],
        deliverables: [
          "Intune blueprint",
          "Rollout plan",
          "Support model documentation",
        ],
      },
      {
        id: "intune-implementation",
        title: "Intune Baseline Implementation",
        shortTitle: "Intune Setup",
        description: "Complete Intune deployment with security baselines, compliance policies, and app management.",
        outcome: "Modern endpoint management with security-first configuration.",
        icon: "device",
        category: "intune",
        types: ["implementation"],
        timeframe: "2-4 weeks",
        includes: [
          "Tenant configuration",
          "Enrollment setup",
          "Security baselines",
          "Compliance policies",
          "App deployment",
        ],
        deliverables: [
          "Configured Intune tenant",
          "Security baseline policies",
          "Compliance policies",
          "App deployment configuration",
          "Rollout documentation",
        ],
        featured: true,
      },
      {
        id: "device-mobile-security",
        title: "Device & Mobile Security Package",
        shortTitle: "Mobile Security",
        description: "Comprehensive device compliance and protection across all platforms.",
        outcome: "Consistent security across iOS, iPadOS, Android, and Windows devices.",
        icon: "smartphone",
        category: "intune",
        types: ["implementation"],
        timeframe: "2-3 weeks",
        includes: [
          "Device compliance policies",
          "App protection policies",
          "Lost device response procedures",
          "Local admin reduction strategy",
          "LAPS approach (Windows)",
        ],
        deliverables: [
          "Compliance model",
          "Policies",
          "Rollout rings",
          "Admin runbook",
        ],
      },
      {
        id: "endpoint-hardening",
        title: "Endpoint Hardening for Windows 10/11",
        shortTitle: "Windows Hardening",
        description: "Security baseline implementation for Windows endpoints.",
        outcome: "Hardened Windows devices with industry-standard security configurations.",
        icon: "shield-device",
        category: "intune",
        types: ["implementation"],
        timeframe: "1-2 weeks",
        includes: [
          "Security baseline deployment",
          "Attack surface reduction rules",
          "BitLocker configuration",
          "Application control guidance",
        ],
        deliverables: [
          "Baseline configuration",
          "ASR rules",
          "BitLocker policies",
          "Hardening documentation",
        ],
      },
      {
        id: "zero-trust-starter",
        title: "Zero Trust Starter (Device Compliance + CA)",
        shortTitle: "Zero Trust Starter",
        description: "Foundation for zero trust with device compliance integrated into Conditional Access.",
        outcome: "Access controlled by device health and compliance status.",
        icon: "verify",
        category: "intune",
        types: ["implementation"],
        timeframe: "1-2 weeks",
        includes: [
          "Device compliance policies",
          "Conditional Access integration",
          "Compliance-based access rules",
        ],
        deliverables: [
          "Compliance policies",
          "CA policies",
          "Zero trust baseline documentation",
        ],
      },
      {
        id: "managed-intune-operations",
        title: "Managed Intune Operations",
        shortTitle: "Intune Operations",
        description: "Ongoing management to keep policies clean, devices compliant, and changes controlled.",
        outcome: "Healthy endpoint environment with proactive maintenance.",
        icon: "settings",
        category: "intune",
        types: ["managed"],
        timeframe: "Monthly",
        includes: [
          "Monthly health review",
          "Policy drift control",
          "Reporting",
          "Change request handling",
        ],
        deliverables: [
          "Monthly endpoint posture report",
          "Improvement backlog",
        ],
      },
    ],
  },

  // 4. IDENTITY & ACCESS (Entra ID)
  {
    id: "identity",
    title: "Identity & Access (Entra ID)",
    shortTitle: "Identity",
    description: "Secure your identity foundation with Entra ID hardening and governance.",
    icon: "user",
    color: "emerald",
    services: [
      {
        id: "entra-security-assessment",
        title: "Entra ID Security Assessment",
        shortTitle: "Entra Assessment",
        description: "Comprehensive review of your Entra ID security posture and configuration.",
        outcome: "Clear understanding of identity risks with prioritized remediation.",
        icon: "user-search",
        category: "identity",
        types: ["assessment"],
        timeframe: "3-5 days",
        includes: [
          "Authentication method review",
          "Conditional Access assessment",
          "Role and permission analysis",
          "Guest access review",
          "App consent evaluation",
        ],
        deliverables: [
          "Security findings report",
          "Risk prioritization",
          "Remediation roadmap",
        ],
      },
      {
        id: "oauth-consent-cleanup",
        title: "OAuth App & Consent Risk Cleanup",
        shortTitle: "OAuth Cleanup",
        description: "Remove risky third-party access and lock down consent pathways.",
        outcome: "Cleaned up enterprise apps with proper consent governance.",
        icon: "app-lock",
        category: "identity",
        types: ["implementation"],
        timeframe: "1 week",
        includes: [
          "Enterprise apps review",
          "Permission grants review",
          "Consent settings recommendations",
          "Cleanup actions",
        ],
        deliverables: [
          "Risky apps list",
          "Changes applied",
          "Governance recommendations",
        ],
      },
      {
        id: "sso-onboarding",
        title: "SSO Onboarding (Per App) + Secure Access Standard",
        shortTitle: "SSO Setup",
        description: "Onboard applications to SSO with consistent security standards.",
        outcome: "Applications integrated with Entra ID SSO and proper access controls.",
        icon: "link",
        category: "identity",
        types: ["implementation"],
        timeframe: "Per app",
        includes: [
          "Application assessment",
          "SSO configuration",
          "Conditional Access integration",
          "User provisioning setup",
        ],
        deliverables: [
          "SSO configuration",
          "Access policies",
          "User documentation",
        ],
      },
      {
        id: "identity-governance",
        title: "Identity Governance & Lifecycle",
        shortTitle: "ID Governance",
        description: "Implement identity governance for access reviews, entitlements, and lifecycle management.",
        outcome: "Governed identity lifecycle with automated access reviews.",
        icon: "user-check",
        category: "identity",
        types: ["implementation"],
        timeframe: "2-4 weeks",
        includes: [
          "Access review configuration",
          "Entitlement management setup",
          "Lifecycle workflow design",
        ],
        deliverables: [
          "Governance policies",
          "Access review schedules",
          "Lifecycle documentation",
        ],
      },
    ],
  },

  // 5. GOOGLE WORKSPACE SERVICES
  {
    id: "google-workspace",
    title: "Google Workspace Services",
    shortTitle: "Google Workspace",
    description: "Security and management services for Google Workspace environments.",
    icon: "google",
    color: "orange",
    services: [
      {
        id: "google-tenant-management",
        title: "Google Workspace Tenant Management",
        shortTitle: "Google Management",
        description: "Operational ownership of Google Admin with security posture maintained.",
        outcome: "Professionally managed Google Workspace with ongoing security.",
        icon: "google",
        category: "google-workspace",
        types: ["managed"],
        timeframe: "Monthly",
        includes: [
          "Admin roles management",
          "Authentication posture",
          "Sharing controls",
          "Lifecycle management",
          "Reporting",
        ],
        deliverables: [
          "Monthly tenant report",
          "Change log",
        ],
      },
      {
        id: "google-security-assessment",
        title: "Google Workspace Security Assessment",
        shortTitle: "Google Assessment",
        description: "Understand exposure and tighten baseline controls in Google Workspace.",
        outcome: "Clear security posture with prioritized fixes.",
        icon: "search",
        category: "google-workspace",
        types: ["assessment"],
        timeframe: "3-5 days",
        includes: [
          "Admin role review",
          "MFA posture assessment",
          "Sharing and external access review",
          "Suspicious apps check",
          "Audit/logging posture",
        ],
        deliverables: [
          "Risk register",
          "Top fixes backlog",
        ],
      },
    ],
  },

  // 6. MIGRATION SERVICES
  {
    id: "migration",
    title: "Migration Services",
    shortTitle: "Migration",
    description: "High-value platform migrations with minimal disruption.",
    icon: "migration",
    color: "rose",
    services: [
      {
        id: "google-microsoft-migration",
        title: "Google to Microsoft Migration",
        shortTitle: "G2M Migration",
        description: "Move users and data from Google Workspace to Microsoft 365 with minimal disruption.",
        outcome: "Complete migration with identity, mail, and data preserved.",
        icon: "migration",
        category: "migration",
        types: ["implementation"],
        timeframe: "2-6 weeks",
        includes: [
          "Identity strategy",
          "Mail migration approach",
          "Drive/Shared Drives strategy",
          "Coexistence plan",
          "Cutover and communications",
        ],
        deliverables: [
          "Migration plan",
          "Executed migration",
          "Post-migration checklist",
          "Support window",
        ],
        featured: true,
      },
      {
        id: "tenant-consolidation",
        title: "Microsoft Tenant Consolidation / Restructure",
        shortTitle: "Tenant Consolidation",
        description: "Fix messy tenant structures with proper governance and security.",
        outcome: "Clean tenant structure with consistent governance.",
        icon: "merge",
        category: "migration",
        types: ["implementation"],
        timeframe: "4-12 weeks",
        includes: [
          "Governance review",
          "Identity model design",
          "Access model cleanup",
          "Workload cleanup plan",
        ],
        deliverables: [
          "Target operating model",
          "Phased roadmap",
          "Implementation sprints",
        ],
      },
    ],
  },

  // 7. NETWORKING, HARDWARE & PHYSICAL TECH (UniFi-led)
  {
    id: "networking",
    title: "Networking & Site Technology",
    shortTitle: "Networking",
    description: "Enterprise-grade networking and site technology delivery with UniFi.",
    icon: "network",
    color: "blue",
    services: [
      {
        id: "unifi-design",
        title: "UniFi Full Stack Design",
        shortTitle: "UniFi Design",
        description: "Complete design for Wi-Fi, switching, routing, segmentation, and site technology.",
        outcome: "Professional network design ready for implementation.",
        icon: "blueprint",
        category: "networking",
        types: ["assessment"],
        timeframe: "1-2 weeks",
        includes: [
          "Requirements gathering",
          "Segmentation plan",
          "Hardware specification",
          "Rollout stages",
        ],
        deliverables: [
          "Design document",
          "Bill of materials",
          "Deployment plan",
        ],
      },
      {
        id: "unifi-implementation",
        title: "UniFi Implementation & Secure Configuration",
        shortTitle: "UniFi Deploy",
        description: "Professional UniFi deployment with security hardening.",
        outcome: "Installed, secured, and documented network infrastructure.",
        icon: "network",
        category: "networking",
        types: ["implementation"],
        timeframe: "1-2 weeks",
        includes: [
          "Gateway configuration",
          "Switching setup",
          "Wi-Fi deployment",
          "VLAN segmentation",
          "Guest/IoT isolation",
          "Remote management setup",
          "Configuration backup",
        ],
        deliverables: [
          "Network configuration",
          "Network diagrams",
          "Handover pack",
        ],
        featured: true,
      },
      {
        id: "unifi-site-tech",
        title: "UniFi Site Technology Deployment",
        shortTitle: "Site Tech",
        description: "End-to-end site technology including cameras, access control, and phones.",
        outcome: "Complete site technology stack from a single provider.",
        icon: "building",
        category: "networking",
        types: ["implementation"],
        timeframe: "1-4 weeks",
        includes: [
          "Wi-Fi and switching",
          "Camera systems",
          "Access control",
          "Phone systems",
          "Digital signage",
        ],
        deliverables: [
          "Deployed systems",
          "Admin documentation",
          "Support plan option",
        ],
      },
      {
        id: "managed-network-operations",
        title: "Managed Network Operations",
        shortTitle: "Network Ops",
        description: "Stable network with proactive maintenance and controlled changes.",
        outcome: "Healthy network infrastructure with ongoing support.",
        icon: "settings",
        category: "networking",
        types: ["managed"],
        timeframe: "Monthly",
        includes: [
          "Config backup management",
          "Firmware strategy",
          "Monitoring",
          "Change requests",
          "Quarterly improvements",
        ],
        deliverables: [
          "Monthly health report",
          "Change log",
        ],
      },
    ],
  },

  // 8. WEB SECURITY & DELIVERY
  {
    id: "web-security",
    title: "Web Security & Delivery",
    shortTitle: "Web Security",
    description: "Application security testing and secure development practices.",
    icon: "globe",
    color: "purple",
    services: [
      {
        id: "web-vulnerability-monitoring",
        title: "Web Vulnerability Monitoring",
        shortTitle: "Web Monitoring",
        description: "Keep your public web footprint clean as dependencies and threats change.",
        outcome: "Ongoing visibility into web application security.",
        icon: "globe-shield",
        category: "web-security",
        types: ["managed"],
        timeframe: "Monthly",
        includes: [
          "Recurring vulnerability scans",
          "Monthly findings analysis",
          "Retest validation",
        ],
        deliverables: [
          "Monthly web security report",
          "Remediation list",
        ],
      },
      {
        id: "web-app-assessment",
        title: "Web Application Security Assessment",
        shortTitle: "Web App Test",
        description: "Security testing for web applications to identify vulnerabilities.",
        outcome: "Identified vulnerabilities with clear remediation guidance.",
        icon: "search-code",
        category: "web-security",
        types: ["assessment"],
        timeframe: "1-2 weeks",
        includes: [
          "OWASP Top 10 testing",
          "Authentication testing",
          "Authorization testing",
          "Input validation testing",
        ],
        deliverables: [
          "Findings report",
          "Remediation guide",
          "Retest option",
        ],
      },
      {
        id: "secure-cicd-review",
        title: "Secure CI/CD and Secrets Hygiene Review",
        shortTitle: "CI/CD Security",
        description: "Reduce supply-chain and credential leakage risk in your development pipeline.",
        outcome: "Secured development pipeline with proper secrets management.",
        icon: "git",
        category: "web-security",
        types: ["assessment"],
        timeframe: "3-5 days",
        includes: [
          "Repository hygiene review",
          "Secrets scanning approach",
          "Deployment pipeline review",
          "Environment separation guidance",
        ],
        deliverables: [
          "Findings report",
          "Remediation checklist",
        ],
      },
    ],
  },

  // 9. SECURE CONFIGURATION REVIEWS
  {
    id: "configuration-reviews",
    title: "Secure Configuration Reviews",
    shortTitle: "Config Reviews",
    description: "Quick, repeatable configuration assessments for common platforms.",
    icon: "check",
    color: "emerald",
    services: [
      {
        id: "secure-defaults-review",
        title: "Secure Defaults vs Conditional Access Review",
        shortTitle: "Defaults Review",
        description: "Confirm you're not relying on weak security defaults.",
        outcome: "Clear understanding of default vs policy-based security.",
        icon: "check-square",
        category: "configuration-reviews",
        types: ["assessment"],
        timeframe: "1-2 days",
        deliverables: [
          "Baseline scorecard",
          "Recommended target state",
        ],
      },
      {
        id: "sharepoint-sharing-review",
        title: "SharePoint External Sharing Safety Review",
        shortTitle: "Sharing Review",
        description: "Enable collaboration without accidental data exposure.",
        outcome: "Secure sharing configuration with proper controls.",
        icon: "share",
        category: "configuration-reviews",
        types: ["assessment", "implementation"],
        timeframe: "2-3 days",
        deliverables: [
          "Settings review",
          "Changes list",
          "Retest confirmation",
        ],
      },
      {
        id: "teams-security-review",
        title: "Teams External/Federation/Meeting Security Review",
        shortTitle: "Teams Review",
        description: "Reduce meeting and external chat risk in Microsoft Teams.",
        outcome: "Secured Teams environment with appropriate external controls.",
        icon: "video",
        category: "configuration-reviews",
        types: ["assessment", "implementation"],
        timeframe: "2-3 days",
        deliverables: [
          "Policy pack",
          "Rollout plan",
        ],
      },
      {
        id: "vpn-remote-access-review",
        title: "VPN / Remote Access Security Review",
        shortTitle: "VPN Review",
        description: "Reduce exposure and tighten remote access security.",
        outcome: "Hardened remote access with documented controls.",
        icon: "lock",
        category: "configuration-reviews",
        types: ["assessment"],
        timeframe: "2-3 days",
        deliverables: [
          "Architecture review",
          "Hardening actions",
          "Runbook",
        ],
      },
      {
        id: "firewall-segmentation-review",
        title: "Firewall Rules and Network Segmentation Review",
        shortTitle: "Firewall Review",
        description: "Reduce lateral movement risk with proper network segmentation.",
        outcome: "Improved network security with clear segmentation.",
        icon: "firewall",
        category: "configuration-reviews",
        types: ["assessment"],
        timeframe: "3-5 days",
        deliverables: [
          "Segmentation improvements",
          "Rules cleanup plan",
        ],
      },
    ],
  },

  // 10. AI SERVICES
  {
    id: "ai-services",
    title: "AI Services",
    shortTitle: "AI Services",
    description: "Practical AI strategy, governance, and implementation - not hype.",
    icon: "ai",
    color: "purple",
    services: [
      {
        id: "ai-readiness-strategy",
        title: "AI Readiness & Strategy",
        shortTitle: "AI Strategy",
        description: "A real AI plan tied to business workflows, not hype.",
        outcome: "Clear AI roadmap with prioritized use cases and implementation plan.",
        icon: "ai",
        category: "ai-services",
        types: ["assessment"],
        timeframe: "2-4 weeks",
        includes: [
          "Use-case discovery",
          "Data readiness assessment",
          "Risk and governance review",
          "Tool selection guidance",
          "Pilot plan development",
        ],
        deliverables: [
          "AI roadmap",
          "Prioritised use cases",
          "Pilot plan",
          "Success metrics",
        ],
        featured: true,
      },
      {
        id: "ai-governance-baseline",
        title: "AI Governance & Security Baseline",
        shortTitle: "AI Governance",
        description: "AI adoption without data leakage and shadow AI chaos.",
        outcome: "Governed AI usage with proper controls and policies.",
        icon: "shield-ai",
        category: "ai-services",
        types: ["implementation"],
        timeframe: "1-2 weeks",
        includes: [
          "Acceptable use policy",
          "Data classification alignment",
          "Access controls",
          "Logging/monitoring approach",
          "'What data can AI see?' review",
        ],
        deliverables: [
          "AI governance pack",
          "Controls backlog",
          "Rollout communications",
        ],
      },
      {
        id: "copilot-readiness",
        title: "Microsoft 365 Copilot Readiness",
        shortTitle: "Copilot Ready",
        description: "Make Copilot useful and safe from day one.",
        outcome: "Environment ready for secure Copilot deployment.",
        icon: "sparkle",
        category: "ai-services",
        types: ["assessment", "implementation"],
        timeframe: "2-4 weeks",
        includes: [
          "SharePoint/OneDrive permissions hygiene",
          "Sensitivity labels approach",
          "Data exposure review",
          "Adoption plan",
        ],
        deliverables: [
          "Copilot readiness report",
          "Remediation backlog",
          "Pilot rollout plan",
        ],
        featured: true,
      },
      {
        id: "ai-workflow-automation",
        title: "AI Workflow Automation",
        shortTitle: "AI Automation",
        description: "Replace manual processes with AI-assisted workflows.",
        outcome: "Automated workflows with AI integration and audit trail.",
        icon: "workflow",
        category: "ai-services",
        types: ["implementation"],
        timeframe: "2-6 weeks",
        includes: [
          "Workflow mapping",
          "Automation build",
          "Approval flows",
          "Auditability setup",
        ],
        deliverables: [
          "Implemented workflows",
          "Documentation",
          "Handover",
        ],
      },
      {
        id: "ai-pilot-program",
        title: "AI Pilot Program",
        shortTitle: "AI Pilot",
        description: "Controlled pilot with measured outcomes and safe controls.",
        outcome: "Proven AI value with clear path to scale.",
        icon: "rocket",
        category: "ai-services",
        types: ["implementation"],
        timeframe: "30-60 days",
        includes: [
          "Pilot group selection",
          "Success metrics definition",
          "Feedback loop",
          "Iteration plan",
        ],
        deliverables: [
          "Pilot results report",
          "Scale plan",
        ],
      },
      {
        id: "ai-training",
        title: "AI Training for Staff",
        shortTitle: "AI Training",
        description: "Practical AI training so people use it safely and effectively.",
        outcome: "Staff competent in AI tools with security awareness.",
        icon: "graduation",
        category: "ai-services",
        types: ["implementation"],
        timeframe: "1-2 sessions",
        includes: [
          "Role-based training",
          "Common task prompts",
          "Security do's and don'ts",
        ],
        deliverables: [
          "Training session",
          "Take-home guide",
          "Policy acknowledgment flow",
        ],
      },
    ],
  },

  // 11. INCIDENT RESPONSE
  {
    id: "incident-response",
    title: "Incident Response",
    shortTitle: "Incident Response",
    description: "Preparation and rapid response for security incidents.",
    icon: "alert",
    color: "rose",
    services: [
      {
        id: "ir-workshop",
        title: "Incident Response Workshop & Tabletop",
        shortTitle: "IR Workshop",
        description: "Prepare your team for security incidents with realistic scenarios.",
        outcome: "Tested response procedures with identified improvement areas.",
        icon: "presentation",
        category: "incident-response",
        types: ["assessment"],
        timeframe: "Half-day",
        includes: [
          "Current state review",
          "Tabletop exercise",
          "Gap identification",
          "Improvement recommendations",
        ],
        deliverables: [
          "Workshop report",
          "Gap analysis",
          "Improvement plan",
        ],
      },
      {
        id: "compromise-assessment",
        title: "Compromise Assessment (Rapid)",
        shortTitle: "Compromise Check",
        description: "Answer 'are we currently breached?' quickly.",
        outcome: "Clear answer on compromise status with containment actions.",
        icon: "search-alert",
        category: "incident-response",
        types: ["assessment"],
        timeframe: "2-3 days",
        includes: [
          "Sign-in review",
          "Suspicious mail rules check",
          "Risky OAuth apps check",
          "Baseline triage plan",
        ],
        deliverables: [
          "Findings report",
          "Containment actions",
          "Next steps",
        ],
      },
      {
        id: "incident-response-retainer",
        title: "Incident Response Retainer",
        shortTitle: "IR Retainer",
        description: "Priority access and prepared runbooks before something goes wrong.",
        outcome: "Rapid response capability with pre-established procedures.",
        icon: "phone-alert",
        category: "incident-response",
        types: ["managed"],
        timeframe: "Monthly/Quarterly",
        includes: [
          "Agreed response hours",
          "IR plan development",
          "Tabletop exercises",
          "Periodic readiness checks",
        ],
        deliverables: [
          "Agreed response hours",
          "IR plan and runbooks",
          "Tabletop exercise",
          "Readiness checks",
        ],
        featured: true,
      },
    ],
  },

  // 12. MODULAR MICROSOFT WORKLOAD SERVICES
  {
    id: "workload-services",
    title: "Microsoft Workload Services",
    shortTitle: "Workload Services",
    description: "Every Microsoft workload as a modular service - assess, implement, or manage.",
    icon: "grid",
    color: "blue",
    services: [
      {
        id: "exchange-online-security",
        title: "Exchange Online Security",
        shortTitle: "Exchange Security",
        description: "Secure your Exchange Online environment with hardened configuration.",
        outcome: "Protected email platform with proper security controls.",
        icon: "mail",
        category: "workload-services",
        types: ["assessment", "implementation", "managed"],
        timeframe: "Varies",
        deliverables: [
          "Security assessment",
          "Hardening implementation",
          "Managed operations",
        ],
      },
      {
        id: "azure-security-baseline",
        title: "Azure Subscription Security Baseline",
        shortTitle: "Azure Security",
        description: "Secure Azure subscriptions with proper IAM and logging.",
        outcome: "Hardened Azure environment with proper governance.",
        icon: "cloud",
        category: "workload-services",
        types: ["assessment", "implementation"],
        timeframe: "1-2 weeks",
        includes: [
          "Subscription review",
          "IAM assessment",
          "Logging configuration",
          "Policy baseline",
        ],
        deliverables: [
          "Security findings",
          "Baseline configuration",
          "Governance recommendations",
        ],
      },
      {
        id: "avd-windows365-security",
        title: "AVD / Windows 365 Security",
        shortTitle: "AVD Security",
        description: "Secure virtual desktop environments with proper controls.",
        outcome: "Protected virtual desktop infrastructure.",
        icon: "desktop",
        category: "workload-services",
        types: ["assessment", "implementation"],
        timeframe: "1-2 weeks",
        deliverables: [
          "Security assessment",
          "Hardening configuration",
          "Access controls",
        ],
      },
    ],
  },
];

// Helper function to get all services across categories
export function getAllServices(): Service[] {
  return SERVICE_CATEGORIES.flatMap(cat => cat.services);
}

// Helper function to get featured services
export function getFeaturedServices(): Service[] {
  return getAllServices().filter(s => s.featured);
}

// Helper function to get services by category
export function getServicesByCategory(categoryId: string): Service[] {
  const category = SERVICE_CATEGORIES.find(c => c.id === categoryId);
  return category ? category.services : [];
}

// Helper function to get a single service by ID
export function getServiceById(serviceId: string): Service | undefined {
  return getAllServices().find(s => s.id === serviceId);
}

// Category icons mapping for components
export const CATEGORY_ICONS = {
  "managed-security": "shield",
  "microsoft-365": "microsoft",
  "intune": "device",
  "identity": "user",
  "google-workspace": "google",
  "migration": "migration",
  "networking": "network",
  "web-security": "globe",
  "configuration-reviews": "check",
  "ai-services": "ai",
  "incident-response": "alert",
  "workload-services": "grid",
};

// Category colors mapping
export const CATEGORY_COLORS = {
  "managed-security": "blue",
  "microsoft-365": "purple",
  "intune": "cyan",
  "identity": "emerald",
  "google-workspace": "orange",
  "migration": "rose",
  "networking": "blue",
  "web-security": "purple",
  "configuration-reviews": "emerald",
  "ai-services": "purple",
  "incident-response": "rose",
  "workload-services": "blue",
};

// Stats for homepage
export const SITE_STATS = [
  { value: "12", label: "Service Categories" },
  { value: "60+", label: "Productized Services" },
  { value: "24/7", label: "Support Available" },
  { value: "100%", label: "Fixed Pricing" },
];

// Partners/Certifications
export const PARTNERS = [
  "Microsoft Partner",
  "UniFi Certified",
  "Cloudflare Partner",
];
